module.exports.config = {
  name: "mahiru",
  version: "1.0.1",
  hasPermssion: 0,
  credits: "Vihoo",
  description: "Random ảnh mahiru",
  commandCategory: "NO PREFIX",
  usages: "mahiru",
  cooldowns: 0,
  denpendencies: {
    "fs-extra": "",
    "request": ""
  }

};
module.exports.handleEvent = async ({ api, event, Threads }) => {
  if (event.body.indexOf("Mahiru")==0 || (event.body.indexOf("mahiru")==0)) {
    const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
    var link = [
      "https://i.imgur.com/5mco4ZC.jpg",
      "https://i.imgur.com/djuYddp.jpg",
      "https://i.imgur.com/1Y1l03y.jpg",
      "https://i.imgur.com/UtIsTeL.jpg",
      "https://i.imgur.com/bGjDoeb.jpg",
      "https://i.imgur.com/pBBtb83.jpg",
      "https://i.imgur.com/2OWAUAD.jpg",
      "https://i.imgur.com/l2RQGYJ.jpg",
      "https://i.imgur.com/tojIn2b.jpg",
      "https://i.imgur.com/msxfjRY.jpg",
      "https://i.imgur.com/NVsg3XU.jpg",
      "https://i.imgur.com/vPEfhIT.jpg",
      "https://i.imgur.com/bO1JOMp.jpg",
      "https://i.imgur.com/gXt3FWu.jpg",
      "https://i.imgur.com/lK0LUsB.jpg",
      "https://i.imgur.com/HsjKwfv.jpg",
      "https://i.imgur.com/ibSoyZJ.jpg",
      "https://i.imgur.com/2JsleGq.jpg",
      "https://i.imgur.com/nGYJmKD.jpg",
      "https://i.imgur.com/OGi1vVf.jpg",
      "https://i.imgur.com/By2wpSK.jpg",
      "https://i.imgur.com/GE5Tvsa.jpg",
      "https://i.imgur.com/ntjfsf3.jpg",
      "https://i.imgur.com/NdMlMNa.jpg",
      "https://i.imgur.com/cJKzii8.jpg",
      "https://i.imgur.com/j3Sdioi.jpg",
      "https://i.imgur.com/Q6BFPUx.jpg",
      "https://i.imgur.com/QLuPXtI.jpg",
      "https://i.imgur.com/Ddn2apL.jpg",
      "https://i.imgur.com/gW2necz.jpg", 
      "https://i.imgur.com/904bZTq.jpg",
      "https://i.imgur.com/er8QuBe.jpg",
      "https://i.imgur.com/pxHOgji.jpg",
      "https://i.imgur.com/nkIaQe2.jpg",
      "https://i.imgur.com/xqFhbIY.jpg",
      "https://i.imgur.com/qLAQEjW.jpg",
      "https://i.imgur.com/vyZNpnU.jpg",
      "https://i.imgur.com/Z3uHYeJ.jpg",
      "https://i.imgur.com/aHV6vqE.jpg",
      "https://i.imgur.com/nFC7KQN.jpg",
      "https://i.imgur.com/UD1cNP1.jpg",
      "https://i.imgur.com/SUWobua.jpg",
      "https://i.imgur.com/niJSrpj.jpg",
      "https://i.imgur.com/XHxVx2X.jpg",
      "https://i.imgur.com/4X9dTJd.jpg",
      "https://i.imgur.com/X7tsaf1.jpg",
      "https://i.imgur.com/egTkvx3.jpg",
      "https://i.imgur.com/rWJsWak.jpg",
      "https://i.imgur.com/v6XKCbt.jpg",
      "https://i.imgur.com/u4lGupL.jpg",
      "https://i.imgur.com/R4WlOu5.jpg",
      "https://i.imgur.com/kIN2GMn.jpg",
      "https://i.imgur.com/M8iISIj.jpg",
      "https://i.imgur.com/eVU8HQO.jpg",
      "https://i.imgur.com/Cm7yQAm.jpg",
      "https://i.imgur.com/PMQh7kf.jpg",
      "https://i.imgur.com/8ILqHJL.jpg",
      "https://i.imgur.com/K8ZB1bt.jpg",
      "https://i.imgur.com/xxTb3SI.jpg",
      "https://i.imgur.com/hMZYZp6.jpg",
      "https://i.imgur.com/7zT2yNe.jpg",
      "https://i.imgur.com/GXuqlDj.jpg",
      "https://i.imgur.com/AZVWxpk.jpg",
      "https://i.imgur.com/G4nlGVs.jpg",
      "https://i.imgur.com/onEMxCX.jpg",
      "https://i.imgur.com/SL02Gwv.jpg",
      "https://i.imgur.com/tJSS6Bu.jpg",
      "https://i.imgur.com/QqSxTFJ.jpg",
      "https://i.imgur.com/2JuNbzd.jpg",
      "https://i.imgur.com/LROGrsO.jpg",
      "https://i.imgur.com/c9HLWn1.jpg",
      "https://i.imgur.com/BpIuNBB.jpg",
      "https://i.imgur.com/ciOXrdZ.jpg",
      "https://i.imgur.com/bLCvNbQ.jpg",
      "https://i.imgur.com/hkQ3Stm.jpg",
      "https://i.imgur.com/UzFpdG3.jpg",
      "https://i.imgur.com/s237VeA.jpg",
      "https://i.imgur.com/EKHls0k.jpg",
      "https://i.imgur.com/GkrYVnZ.jpg",
      "https://i.imgur.com/3hMALHv.jpg",
      "https://i.imgur.com/sCmfxuF.jpg",
      "https://i.imgur.com/gOx9UHL.jpg",
      "https://i.imgur.com/WxGDBlo.jpg",
      "https://i.imgur.com/YjM3MYX.jpg",
      "https://i.imgur.com/OueTDlp.jpg",
      "https://i.imgur.com/IUP8qfA.jpg",
      "https://i.imgur.com/seMbtiq.jpg",
      "https://i.imgur.com/25AP193.jpg",
      "https://i.imgur.com/X4UwWh4.jpg",
      "https://i.imgur.com/xZStCHG.jpg",
      "https://i.imgur.com/bucF7O7.jpg",
      "https://i.imgur.com/jgNTh8H.jpg",
      "https://i.imgur.com/9JWUGCd.jpg",
      "https://i.imgur.com/wL8wJAK.jpg",
      "https://i.imgur.com/cuh8DSb.jpg",
      "https://i.imgur.com/4IvQyIy.jpg",
      "https://i.imgur.com/DAmGusO.jpg",
      "https://i.imgur.com/QawM14X.jpg",
      "https://i.imgur.com/zwJycIS.jpg",
      "https://i.imgur.com/4klnILt.jpg",
      "https://i.imgur.com/DXT4NMk.jpg",
      "https://i.imgur.com/PFITEDK.jpg",
      "https://i.imgur.com/4cwIpKr.jpg",
      "https://i.imgur.com/EoUDE4M.jpg",
      "https://i.imgur.com/4u9BsyW.jpg",
      "https://i.imgur.com/lyscyDd.jpg",
      "https://i.imgur.com/RR8rwGp.jpg",
      "https://i.imgur.com/KI7xPQ9.jpg",
      "https://i.imgur.com/xQyqrn9.jpg",
      "https://i.imgur.com/nZ94gW0.jpg",
      "https://i.imgur.com/5orBkm5.jpg",
      "https://i.imgur.com/k4dgFEu.jpg",
      "https://i.imgur.com/Sr2xdBo.jpg",
      "https://i.imgur.com/ZDoP1aD.jpg",
      "https://i.imgur.com/pdzlLim.jpg",
      "https://i.imgur.com/Cdzm2l1.jpg",
      "https://i.imgur.com/SVvviiF.jpg",
      "https://i.imgur.com/UPz4OCp.jpg",
      "https://i.imgur.com/ewnpfgN.jpg",
      "https://i.imgur.com/CnHvqtg.jpg",
      "https://i.imgur.com/3HXKPUR.jpg",
      "https://i.imgur.com/EgDu8jE.jpg",
      "https://i.imgur.com/VK1bRgZ.jpg",
      "https://i.imgur.com/KjsafmY.jpg",
      "https://i.imgur.com/ykdZn87.jpg",
      "https://i.imgur.com/ZhkyNlz.jpg",
      "https://i.imgur.com/U1gKmSk.jpg",
      "https://i.imgur.com/Vy1GrIm.jpg",
      "https://i.imgur.com/j794R3Y.jpg",
      "https://i.imgur.com/rLJCOSk.jpg",
      "https://i.imgur.com/tnyHoOp.jpg",
      "https://i.imgur.com/0gw9pXy.jpg",
      "https://i.imgur.com/irNcNol.jpg",
      "https://i.imgur.com/2taIyx9.jpg",
      "https://i.imgur.com/F55biNg.jpg",
      "https://i.imgur.com/u2Ws7xg.jpg",
      "https://i.imgur.com/b0uUnCb.jpg",
      "https://i.imgur.com/kDItpbz.jpg",
      "https://i.imgur.com/GWe42zu.jpg",
      "https://i.imgur.com/CR4fDAQ.jpg",
      "https://i.imgur.com/fUWY3RP.jpg",
      "https://i.imgur.com/l5t1rLl.jpg",
      "https://i.imgur.com/ET1EX8i.jpg",
      "https://i.imgur.com/wp9racr.jpg",
      "https://i.imgur.com/ZTAvQYb.jpg",
      "https://i.imgur.com/FiApISS.jpg",
      "https://i.imgur.com/QQVm8On.jpg",
      "https://i.imgur.com/QuSQigi.jpg",
      "https://i.imgur.com/GDwup5W.jpg",
      "https://i.imgur.com/RWOzZo3.jpg",
      "https://i.imgur.com/LBoq6Mh.jpg",
      "https://i.imgur.com/oYIx3ZX.jpg",
      "https://i.imgur.com/nyOMQnh.jpg",
      "https://i.imgur.com/v6tAUwC.jpg",
      "https://i.imgur.com/EzUhnYa.jpg",
      "https://i.imgur.com/4SvFRHc.jpg",
      "https://i.imgur.com/mKvoliI.jpg",
      "https://i.imgur.com/buOxINM.jpg",
      "https://i.imgur.com/4NJZ3xv.jpg",
      "https://i.imgur.com/XZzjxEG.jpg",
      "https://i.imgur.com/j2NvSwt.jpg",
      "https://i.imgur.com/JhLA5tF.jpg",
      "https://i.imgur.com/aFh1maE.jpg",
      "https://i.imgur.com/ZoCrbMO.jpg",
      "https://i.imgur.com/Avz6rUd.jpg",
      "https://i.imgur.com/Rp2VNGG.jpg",
      "https://i.imgur.com/TPGZLXd.jpg",
      "https://i.imgur.com/8xOlqZX.jpg",
      "https://i.imgur.com/3vrbzyq.jpg",
      "https://i.imgur.com/N8EProV.jpg",
      "https://i.imgur.com/sCdFkBl.jpg",
      "https://i.imgur.com/f1bJJL1.jpg",
      "https://i.imgur.com/4jPKQCm.jpg",
      "https://i.imgur.com/U9egv49.jpg",
      "https://i.imgur.com/UQCkWmo.jpg",
      "https://i.imgur.com/juinohB.jpg",
      "https://i.imgur.com/A12wwF8.jpg",
      "https://i.imgur.com/ZZmQbXy.jpg",
      "https://i.imgur.com/z6jnHi7.jpg",
      "https://i.imgur.com/2npZ95k.jpg",
      "https://i.imgur.com/dyUcdyo.jpg",
      "https://i.imgur.com/m7CIreW.jpg",
      "https://i.imgur.com/cZxc2XR.jpg",
      "https://i.imgur.com/raKaWjj.jpg",
      "https://i.imgur.com/S72pZkj.jpg",
      "https://i.imgur.com/zCaxZ1k.jpg",
      "https://i.imgur.com/5Y19hnA.jpg",
      "https://i.imgur.com/ZcP6xcb.jpg"
          ];
     var callback = () => api.sendMessage({body:``,attachment: fs.createReadStream(__dirname + "/noprefix/mahiru.jpg")}, event.threadID, () => fs.unlinkSync(__dirname + "/noprefix/mahiru.jpg"), event.messageID);  
      return request(encodeURI(link[Math.floor(Math.random() * link.length)])).pipe(fs.createWriteStream(__dirname+"/noprefix/mahiru.jpg")).on("close",() => callback());
}
                                                                                                         }
module.exports.run = async({api,event,args,Users,Threads,Currencies}) => {

   };