module.exports.config = {
  name: "trai",
  version: "1.0.1",
  hasPermssion: 0,
  credits: "Vihoo",
  description: "Random ảnh trai",
  commandCategory: "NO PREFIX",
  usages: "trai",
  cooldowns: 0,
  denpendencies: {
    "fs-extra": "",
    "request": ""
  }

};
module.exports.handleEvent = async ({ api, event, Threads }) => {
  if (event.body.indexOf("Trai")==0 || (event.body.indexOf("trai")==0)) {
    const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
    var link = [
      "https://i.imgur.com/ENy5vtL.jpg",
      "https://i.imgur.com/pmUI7vG.jpg",
      "https://i.imgur.com/Wdhplwe.jpg",
      "https://i.imgur.com/XyT3tlg.jpg",
      "https://i.imgur.com/oAxI9sh.jpg",
      "https://i.imgur.com/ozqqZZX.jpg",
      "https://i.imgur.com/dqTckRi.jpg",
      "https://i.imgur.com/plViXfW.jpg",
      "https://i.imgur.com/XICwcUw.jpg",
      "https://i.imgur.com/BPPvhYH.jpg",
      "https://i.imgur.com/1EPlwYv.jpg",
      "https://i.imgur.com/2khnfVy.jpg",
      "https://i.imgur.com/0KA5LZ6.jpg",
      "https://i.imgur.com/fXK46Si.jpg",
      "https://i.imgur.com/rgP40E4.jpg",
      "https://i.imgur.com/DTBCa5J.jpg",
      "https://i.imgur.com/zMaCBmM.jpg",
      "https://i.imgur.com/sryvqpw.jpg",
      "https://i.imgur.com/zrH5e9V.jpg",
      "https://i.imgur.com/i9vuhZS.jpg",
      "https://i.imgur.com/9GMPh6J.jpg",
      "https://i.imgur.com/ympPXCY.jpg",
      "https://i.imgur.com/ZkOHZoX.jpg",
      "https://i.imgur.com/gYlbik3.jpg",
      "https://i.imgur.com/tyZuHXh.jpg",
      "https://i.imgur.com/kjRwwga.jpg",
      "https://i.imgur.com/FDJEJwY.jpg",
      "https://i.imgur.com/CtRMgBl.jpg",
      "https://i.imgur.com/qBdQM15.jpg",
      "https://i.imgur.com/BaN9ZyO.jpg",
      "https://i.imgur.com/8ZRAS7a.jpg",
      "https://i.imgur.com/AXi4gL4.jpg",
      "https://i.imgur.com/jOMgfah.jpg",
      "https://i.imgur.com/9v9rPeY.jpg",
      "https://i.imgur.com/AHXRLlQ.jpg",
      "https://i.imgur.com/JVPUWcT.jpg",
      "https://i.imgur.com/dDmU5YP.jpg",
      "https://i.imgur.com/jJoHdz5.jpg",
      "https://i.imgur.com/ELklGyh.jpg",
      "https://i.imgur.com/iIcVOfQ.jpg",
      "https://i.imgur.com/kFOmtlm.jpg",
      "https://i.imgur.com/XS51cDU.jpg",
      "https://i.imgur.com/gV7rmLu.jpg",
      "https://i.imgur.com/frzlIGK.jpg",
      "https://i.imgur.com/SvsBvcd.jpg",
      "https://i.imgur.com/n8nHn2T.jpg",
      "https://i.imgur.com/ntUmOC8.jpg",
      "https://i.imgur.com/K0Roen6.jpg",
      "https://i.imgur.com/Pqdhqkj.jpg",
      "https://i.imgur.com/NF4MUXP.jpg",
      "https://i.imgur.com/cISSFyl.jpg",
      "https://i.imgur.com/WJ0fPt8.jpg",
      "https://i.imgur.com/QuYRo83.jpg",
      "https://i.imgur.com/Zd8V00n.jpg",
      "https://i.imgur.com/qht8UzZ.jpg",
      "https://i.imgur.com/BGOxQnK.jpg",
      "https://i.imgur.com/W4B29VG.jpg",
      "https://i.imgur.com/ZzCo9Rp.jpg",
      "https://i.imgur.com/XMJqYlk.jpg",
      "https://i.imgur.com/pfIbS06.jpg",
      "https://i.imgur.com/bVa25sl.jpg",
      "https://i.imgur.com/q3hIVDq.jpg",
      "https://i.imgur.com/QPbF2Hx.jpg",
      "https://i.imgur.com/0SnKD1r.jpg",
      "https://i.imgur.com/derAl0z.jpg",
      "https://i.imgur.com/WhPg8VB.jpg",
      "https://i.imgur.com/pFaXGzB.jpg",
        "https://i.postimg.cc/CM3L62V6/hinh-anh-nam-than-cua-showbit-viet-085757558.jpg",
      "https://i.imgur.com/RugqIsE.jpg",
      "https://i.imgur.com/blDv1A2.jpg",
      "https://i.imgur.com/J0fqMYW.jpg",
      "https://i.imgur.com/HnBfMR0.jpg",
      "https://i.postimg.cc/LXm8vgK4/Hot-Boy-De-p-Vie-t-Nam-Deo-Ki-nh.jpg",
      "https://i.imgur.com/uQ30ady.jpg",
      "https://i.postimg.cc/wBQ6txtC/A-nh-trai-de-p-vie-t-nam-cha-t.jpg",
      "https://i.imgur.com/g2HOtF6.jpg",
      "https://i.imgur.com/AmY8uZH.jpg",
      "https://i.postimg.cc/PJ9hGPcw/A-nh-Hot-Boy-Vie-t-Nam.jpg",
      "https://i.imgur.com/ufFpS22.jpg",
      "https://i.postimg.cc/2jMfSLcq/hinh-anh-trai-viet-de-thuong-cuc-dep-085758948.jpg",
      "https://i.postimg.cc/tgWsBHsk/5-anh-trai-dep-viet-nam.jpg",
      "https://i.postimg.cc/MZbyW1K5/9-anh-trai-dep-viet-nam.jpg",
      "https://i.postimg.cc/MKrb88zx/anh-trai-dep-viet-nam-cuc-chat-085754761.jpg",
      "https://i.postimg.cc/P58JqkQH/Hot-Boy-De-p-Nha-t-Vie-t-Nam.jpg",
      "https://i.postimg.cc/vZNPXV4r/anh-trai-viet-dep-ngau-ca-tinh-085756209.jpg",
      "https://i.imgur.com/LYkV9VF.jpg",
      "https://i.postimg.cc/MpRZSmzK/Hi-nh-Trai-De-p-Vie-t-Nam-2k-ga-y-ba-o-ma-ng.jpg",
      "https://i.postimg.cc/HxSd2S93/Hi-nh-Trai-De-p-Vie-t-Nam-2k-go-c-vie-t.jpg",
      "https://i.postimg.cc/qv8rYBGN/hinh-anh-trai-viet-nam-dep-nhat-085759732.jpg",
      "https://i.postimg.cc/nL0ybX9h/hinh-anh-trai-dep-viet-nam-cuc-ngau-085758349.jpg",
      "https://i.postimg.cc/DwZjqgwf/anh-trai-viet-dep-trai-lich-lam-085755636.jpg",
      "https://i.imgur.com/mDrBofk.jpg",
      "https://i.imgur.com/okvL0Ly.jpg",
      "https://i.imgur.com/cJErkOY.jpg",
      "https://i.postimg.cc/g0YCTVJ7/hinh-anh-trai-dep-viet-nam-choi-the-thao-085758104.jpg",
      "https://i.postimg.cc/4dFRtYXS/hinh-anh-trai-viet-dep-ca-tinh-085759222.jpg",
      "https://i.postimg.cc/kGnRVhXc/4-anh-trai-dep-viet-nam.jpg",
      "https://i.postimg.cc/PrCr6kcD/Hi-nh-Trai-De-p-Nha-t-Vie-t-Nam-Co-Ma-Lu-m-Do-ng-Tie-n.jpg",
      "https://i.postimg.cc/QxdWhPzN/3-anh-trai-dep-viet-nam.jpg",
      "https://i.postimg.cc/FsKgqK5D/anh-trai-dep-viet-nam-ca-tinh-085754646.jpg",
      "https://i.postimg.cc/fyG421t7/hinh-anh-trai-viet-nam-dep-ca-tinh-nhat-085759845.jpg",
      "https://i.imgur.com/eoVIliQ.jpg",
      "https://i.postimg.cc/wMT3xy04/H-nh-trai-p-cute.jpg",
      "https://i.imgur.com/ffu0IQV.jpg",
      "https://i.imgur.com/GOuzwUe.jpg",
      "https://i.imgur.com/MvjXMnC.jpg",
      "https://i.imgur.com/QPIce66.jpg",
      "https://i.postimg.cc/8czWqZ3j/anh-trai-dep-viet-nam-de-thuong-085754894.jpg",
      "https://i.imgur.com/pwa9Qxj.jpg",
      "https://i.imgur.com/Q12izpx.jpg",
      "https://i.postimg.cc/3w5R4btv/H-nh-trai-Vi-t-Nam-p.jpg",
      "https://i.imgur.com/khII2UE.jpg",
      "https://i.postimg.cc/k4CBZh8m/H-nh-trai-Vi-t-Nam-p-trai.jpg",
      "https://i.postimg.cc/V61XFfW9/anh-hot-boy-quan-su-viet-nam-085753696.jpg",
      "https://i.postimg.cc/K84LrV7p/11-anh-trai-dep-viet-nam.jpg",
      "https://i.postimg.cc/c4jYbMcL/anh-nam-sinh-viet-dep-trai-tua-nhu-giang-than-085754248.jpg",
      "https://i.postimg.cc/bN1NXRyY/anh-trai-viet-thu-sinh-085757320.jpg",
      "https://i.postimg.cc/9F0zv94r/Hot-Boy-Vie-t-Nam-Deo-Ki-nh-Bao-Nga-u.jpg",
      "https://i.imgur.com/eaDOZnC.jpg",
      "https://i.postimg.cc/K8dK7Y84/H-nh-trai-ng-y-u-d-th-ng.jpg",
      "https://i.imgur.com/qPSJTEF.jpg",
      "https://i.postimg.cc/vHX2gjMS/anh-trai-viet-nam-cuc-dep-085756511.jpg",
      "https://i.imgur.com/vi90Mtb.jpg",
      "https://i.imgur.com/Cl64w7g.jpg",
      "https://i.postimg.cc/cC82nT9v/hinh-anh-trai-dep-10x-viet-nam-085757663.jpg",
      "https://i.imgur.com/VFspbfW.jpg",
      "https://i.imgur.com/hutrUcx.jpg",
      "https://i.postimg.cc/QtMrHQZ7/hinh-anh-trai-viet-dep-085759343.jpg",
      "https://i.imgur.com/xkoPbyl.jpg",
      "https://i.postimg.cc/HL1MpYRG/anh-soai-ca-viet-nam-085754392.jpg",
      "https://i.postimg.cc/T2Cp703z/Hot-Boy-VN-Da-u-Na-m.jpg",
      "https://i.postimg.cc/Hkc0YPLM/anh-trai-viet-dep-buon-085755881.jpg",
      "https://i.postimg.cc/Hsv8xzGw/1-anh-trai-dep-viet-nam.jpg",
      "https://i.postimg.cc/BnWsMP2W/hinh-anh-trai-viet-nam-cuc-dep-085759481.jpg",
      "https://i.postimg.cc/VsWDpTSL/anh-trai-dep-viet-nam-085755119.jpg",
      "https://i.postimg.cc/MHDRdJrN/16-anh-trai-dep-viet-nam.jpg",
      "https://i.imgur.com/pmLUEcX.jpg",
      "https://i.postimg.cc/Y0GKxt9q/hinh-anh-trai-viet-de-thuong-085759077.jpg",
      "https://i.postimg.cc/g2PFvFPm/hinh-anh-trai-dep-viet-nam-de-thuong-085758514.jpg",
      "https://i.imgur.com/QSOo3hN.jpg",
      "https://i.postimg.cc/k5smJjz9/hinh-anh-trai-viet-nam-cuc-soai-ca-085759597.jpg",
      "https://i.imgur.com/4pa7ThF.jpg",
      "https://i.postimg.cc/4dCWRRbn/anh-trai-viet-dep-trai-lanh-lung-085755499.jpg",
      "https://i.postimg.cc/4dR9GxDj/7-anh-trai-dep-viet-nam.jpg",
      "https://i.postimg.cc/fLWMY4mJ/Hi-nh-Trai-De-p-Vie-t-Nam-2k-sie-u-cute.jpg",
      "https://i.postimg.cc/zDtGSfd5/A-nh-Hot-Boy-Vie-t-Nam-nu-c-cu-o-i-de-p.jpg",
      "https://i.imgur.com/txI312W.jpg",
      "https://i.postimg.cc/4dwN04s6/Nam-Sinh-De-p-Nha-t-Vie-t-Nam-Cho-i-Da-n.jpg",
      "https://i.postimg.cc/fLy6wMYj/hinh-anh-trai-dep-viet-nam-sieu-chat-085758655.jpg",
      "https://i.imgur.com/3wOuBgV.jpg",
      "https://i.postimg.cc/TY5fVJLq/hinh-anh-trai-viet-nam-dep-de-thuong-085800146.jpg",
      "https://i.imgur.com/3oPVFG3.jpg",
      "https://i.postimg.cc/90Y8Bg90/anh-trai-viet-dep-ngau-085756408.jpg",
      "https://i.imgur.com/fOaL1RC.jpg",
      "https://i.postimg.cc/zX4D6cZc/A-nh-Trai-De-p-Vie-t-Nam-Ho-c-Sinh.jpg",
      "https://i.postimg.cc/C1jmFrm7/anh-trai-viet-nam-dep-kieu-thu-sinh-085756650.jpg",
      "https://i.imgur.com/gmZQoqe.jpg",
      "https://i.postimg.cc/R0HH2HDc/18-anh-trai-dep-viet-nam.jpg",
      "https://i.postimg.cc/c1bdtbHL/hinh-anh-trai-viet-nam-dep-tam-trang-085800272.jpg",
      "https://i.postimg.cc/vHGSmMRV/anh-trai-viet-dep-trai-phong-tran-085755761.jpg",
      "https://i.postimg.cc/90hgZHrs/anh-trai-viet-nam-dep-chat-085756984.jpg",
      "https://i.postimg.cc/ncdTcDYy/anh-trai-dep-viet-nam-lanh-lung-ca-tinh-085755021.jpg",
      "https://i.imgur.com/WIbcx59.jpg",
      "https://i.postimg.cc/L4Y8DpG1/hinh-anh-trai-dep-hoc-sinh-085757801.jpg",
      "https://i.postimg.cc/W4vNbq4m/Hi-nh-Trai-De-p-Vie-t-Nam-2k-cu-c-cha-t.jpg",
      "https://i.imgur.com/VrNREYM.jpg",
      "https://i.postimg.cc/B6q1KhJM/anh-nam-sinh-truong-cong-nghe-khien-van-co-gai-me-met-085754129.jpg",
      "https://i.postimg.cc/8PYsDCWw/Boy-Vi-t-Nam-cute-p-trai-819x1024.jpg",
      "https://i.postimg.cc/HsWBg250/anh-trai-viet-dep-ca-tinh-085756027.jpg",
      "https://i.imgur.com/RP1tpFz.jpg",
      "https://i.postimg.cc/wMfM1qrq/Boy-Vi-t-Nam-p-trai.jpg",
      "https://i.postimg.cc/9FmyzzDh/15-anh-trai-dep-viet-nam.jpg",
      "https://i.postimg.cc/8sQ3BW9t/hinh-anh-con-trai-viet-nam-dep-ngau-085757447.jpg",
      "https://i.imgur.com/jCOlQPw.jpg",
      "https://i.postimg.cc/FHfdJSm2/H-nh-trai-cute.jpg",
      "https://i.postimg.cc/GtrGFmzv/25-anh-trai-dep-viet-nam.jpg",
      "https://i.postimg.cc/ZY8MZnQm/anh-trai-viet-nam-dep-nhat-085756841.jpg",
      "https://i.postimg.cc/sXJvR99Z/H-nh-trai-p-cute-nh-t.jpg",
      "https://i.imgur.com/7QeSlYO.jpg",
      "https://i.postimg.cc/wjLtbKvw/anh-con-trai-viet-nam-dep-ngau-085753465.jpg",
      "https://i.postimg.cc/43GYD8Hs/anh-nam-sinh-lop-10-dep-trai-085754007.jpg",
      "https://i.postimg.cc/2yVmX4HY/A-nh-Hot-Boy-Vie-t-Nam-sie-u-cha-t.jpg",
      "https://i.postimg.cc/D0BJ1dSK/2-anh-trai-dep-viet-nam.jpg",
      "https://i.imgur.com/1j8CNAM.jpg",
      "https://i.postimg.cc/XYm896Px/anh-trai-viet-dep-trai-ca-tinh-085755238.jpg",
      "https://i.postimg.cc/DfgXVFBY/anh-trai-dep-viet-nam.jpg",
      "https://i.postimg.cc/k4HLGLcr/hinh-anh-trai-dep-rmit-085757964.jpg"
          ];
     var callback = () => api.sendMessage({body:``,attachment: fs.createReadStream(__dirname + "/noprefix/trai.jpg")}, event.threadID, () => fs.unlinkSync(__dirname + "/noprefix/trai.jpg"), event.messageID);  
      return request(encodeURI(link[Math.floor(Math.random() * link.length)])).pipe(fs.createWriteStream(__dirname+"/noprefix/trai.jpg")).on("close",() => callback());
}
                                                                                                         }
module.exports.run = async({api,event,args,Users,Threads,Currencies}) => {

   };